from typing import Any, Optional

class CacheHandler:
    def get_cached_token(self) -> None: ...
    def save_token_to_cache(self, token_info: Any) -> None: ...

class CacheFileHandler(CacheHandler):
    cache_path: Any = ...
    def __init__(self, cache_path: Optional[Any] = ..., username: Optional[Any] = ...) -> None: ...
    def get_cached_token(self): ...
    def save_token_to_cache(self, token_info: Any) -> None: ...

class MemoryCacheHandler(CacheHandler):
    token_info: Any = ...
    def __init__(self, token_info: Optional[Any] = ...) -> None: ...
    def get_cached_token(self): ...
    def save_token_to_cache(self, token_info: Any) -> None: ...
